// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>TableauHelper.xsd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Xml.Serialization;

namespace TableauHelper.Api {
    [Serializable()]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public class TsRequest {
        
        private object _itemField;
        
        [XmlElement("connection", typeof(ConnectionType))]
        [XmlElement("credentials", typeof(TableauCredentialsType))]
        [XmlElement("datasource", typeof(DataSourceType))]
        [XmlElement("favorite", typeof(FavoriteType))]
        [XmlElement("group", typeof(GroupType))]
        [XmlElement("permissions", typeof(PermissionsType))]
        [XmlElement("project", typeof(ProjectType))]
        [XmlElement("site", typeof(SiteType))]
        [XmlElement("tags", typeof(TagListType))]
        [XmlElement("user", typeof(UserType))]
        [XmlElement("workbook", typeof(WorkbookType))]
        public object Item {
            get {
                return _itemField;
            }
            set {
                _itemField = value;
            }
        }
    }
}
